export default [
  {
    name: "Idioms",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Idioms.png",
    github: "https://github.com/1alexvash/Idioms",
    live: "https://1alexvash.github.io/Idioms/",
  },
  {
    name: "DecisionMaker",
    technologies: ["HTML", "CSS", "JavaScript", "React.js", "Redux"],
    logo: "images/projects/DecisionMaker.png",
    github: "https://github.com/1alexvash/DecisionMaker",
    live: "https://1alexvash.github.io/DecisionMaker/",
  },
  {
    name: "Spelling",
    technologies: ["HTML", "CSS", "JavaScript", "React.js", "Redux"],
    logo: "images/projects/Spelling.png",
    github: "https://github.com/1alexvash/Spelling",
    live: "https://1alexvash.github.io/Spelling/",
  },
  {
    name: "Conversation",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Conversation.png",
    github: "https://github.com/1alexvash/Conversation",
    live: "https://1alexvash.github.io/Conversation/",
  },
  {
    name: "RandomGenerator",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/RandomGenerator.png",
    github: "https://github.com/1alexvash/RandomGenerator",
    live: "https://1alexvash.github.io/RandomGenerator/",
  },
  {
    name: "IrregularVerbs",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/IrregularVerbs.png",
    github: "https://github.com/1alexvash/IrregularVerbs",
    live: "https://1alexvash.github.io/IrregularVerbs/",
  },
  {
    name: "Quiz",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Quiz.png",
    github: "https://github.com/1alexvash/Quiz",
    live: "https://1alexvash.github.io/Quiz/",
  },
  {
    name: "Memory",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Memory.png",
    github: "https://github.com/1alexvash/Memory",
    live: "https://1alexvash.github.io/Memory/",
  },
  {
    name: "Timers",
    technologies: ["HTML", "CSS", "JavaScript", "React.js", "Redux"],
    logo: "images/projects/Timers.png",
    github: "https://github.com/1alexvash/Timers",
    live: "https://1alexvash.github.io/Timers/",
  },
  {
    name: "Millionaire",
    technologies: ["HTML", "CSS", "JavaScript"],
    logo: "images/projects/Millionaire.png",
    github: "https://github.com/1alexvash/Millionaire",
    live: "https://1alexvash.github.io/Millionaire/",
  },
  {
    name: "Words",
    technologies: ["HTML", "CSS", "JavaScript"],
    logo: "images/projects/Words.png",
    github: "https://github.com/1alexvash/Words",
    live: "https://1alexvash.github.io/Words/",
  },
  {
    name: "Submarine",
    technologies: ["HTML", "CSS", "JavaScript", "Canvas"],
    logo: "images/projects/Submarine.png",
    github: "https://github.com/1alexvash/Submarine",
    live: "https://1alexvash.github.io/Submarine/",
  },
  {
    name: "UrlShortener",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/UrlShortener.png",
    github: "https://github.com/1alexvash/UrlShortener",
    live: "https://1alexvash.github.io/UrlShortener/",
  },
  {
    name: "PasswordGenerator",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/PasswordGenerator.png",
    github: "https://github.com/1alexvash/PasswordGenerator",
    live: "https://1alexvash.github.io/PasswordGenerator/",
  },
  {
    name: "RandomMovie",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/RandomMovie.png",
    github: "https://github.com/1alexvash/RandomMovie",
    live: "https://1alexvash.github.io/RandomMovie/",
  },
  {
    name: "ButtonMaker",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/ButtonMaker.png",
    github: "https://github.com/1alexvash/ButtonMaker",
    live: "https://1alexvash.github.io/ButtonMaker/",
  },
  {
    name: "Notes",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Notes.png",
    github: "https://github.com/1alexvash/Notes",
    live: "https://1alexvash.github.io/Notes/",
  },
  {
    name: "HIIT",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/HIIT.png",
    github: "https://github.com/1alexvash/HIIT",
    live: "https://1alexvash.github.io/HIIT/",
  },
  {
    name: "Weather",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Weather.png",
    github: "https://github.com/1alexvash/Weather",
    live: "https://1alexvash.github.io/Weather/",
  },
  {
    name: "Currencies",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Currencies.png",
    github: "https://github.com/1alexvash/Currencies",
    live: "https://1alexvash.github.io/Currencies/",
  },
  {
    name: "Converter",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Converter.png",
    github: "https://github.com/1alexvash/Converter",
    live: "https://1alexvash.github.io/Converter/",
  },
  {
    name: "DailyJournal",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "React.js",
      "MongoDB",
      "Node.js",
      "express",
      "Redux",
    ],
    logo: "images/projects/DailyJournal.png",
    github: "https://github.com/1alexvash/DailyJournal",
    live: "",
  },
  {
    name: "Math",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Math.png",
    github: "https://github.com/1alexvash/Math",
    live: "https://nextjs-knbmtk9dv.now.sh/",
  },
  {
    name: "Checkers",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Checkers.png",
    github: "https://github.com/1alexvash/Checkers",
    live: "https://1alexvash.github.io/Checkers/",
  },
  {
    name: "Meditation",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Meditation.png",
    github: "https://github.com/1alexvash/Meditation",
    live: "https://1alexvash.github.io/Meditation/",
  },
  {
    name: "Chess",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Chess.png",
    github: "https://github.com/1alexvash/Chess",
    live: "https://1alexvash.github.io/Chess/",
  },
  {
    name: "Typist",
    technologies: ["HTML", "CSS", "JavaScript", "React.js"],
    logo: "images/projects/Typist.png",
    github: "https://github.com/1alexvash/Typist",
    live: "https://1alexvash.github.io/Typist/",
  },
];
